### ISSUE TITLE
Not able to connect through node despite NatNet SampleClient working

### ISSUE THREAD

**Issue by dvdmc** [MOCAP4ROS2-Project/mocap4ros2_optitrack#35]
I'm able to connect with the NatNet SampleClient example included in the [SDK](https://optitrack.com/software/natnet-sdk/) using automatic discovery and specifying the server IP.
However, when I run the node with the same configuration (Uni/Multicast, server IP, local IP and ports) I get a Network error code. So I guess the problem is not on the network side unless ROS is changing anything.

The logger from the SampleClient:
`SampleClient.cpp` (works):
```
NatNet Sample Client (NatNet ver. 4.1.0.0)
Using server at 192.168.0.100
Using local address 

[NatNetLib]  [INFO]: [Client] Initializing using local address: 192.168.0.150

[NatNetLib]  [INFO]: [Client] Initializing command listener.

[NatNetLib] [ERROR]: Socket error 0: Success

[NatNetLib] [ERROR]: [Client] Receive Buffer Size: 425984

[NatNetLib]  [INFO]: [Client] Host information received. (HostApp: Motive  HostVer: 3.1.0.1  HostIP: 192.168.0.100 ()

[NatNetLib]  [INFO]: [Client] Initializing data listener.

[NatNetLib]  [WARN]: [HELPER] ReceiveBuffer size = 425984

[NatNetLib]  [INFO]: [Client] Connected.

[SampleClient] Server application info:
Application: Motive (ver. 3.1.0.1)
NatNet Version: 4.1.0.0
Client IP:
Server IP:192.168.0.100
Server Name:
Mocap Framerate : 120.00
Client initialized and ready.
```

Including the logger from the SampleClient.cpp I get the following logs:
`MOCAP4ROS2` (doesn't work):
```
[mocap4r2_optitrack_driver_main-1] [NatNetLib]  [INFO]: [Client] Initializing using local address: 192.168.0.150
[mocap4r2_optitrack_driver_main-1] 
[mocap4r2_optitrack_driver_main-1] [NatNetLib]  [INFO]: [Client] Initializing command listener.
[mocap4r2_optitrack_driver_main-1] 
[mocap4r2_optitrack_driver_main-1] [NatNetLib] [ERROR]: Socket error 25: Inappropriate ioctl for device
[mocap4r2_optitrack_driver_main-1] 
[mocap4r2_optitrack_driver_main-1] [NatNetLib] [ERROR]: [Client] Receive Buffer Size: 425984
[mocap4r2_optitrack_driver_main-1] 
[mocap4r2_optitrack_driver_main-1] [NatNetLib] [DEBUG]: SetCurrentThreadName not implemented for this platform.
[mocap4r2_optitrack_driver_main-1] 
[mocap4r2_optitrack_driver_main-1] [NatNetLib] [ERROR]: [Client] Timed out while connecting to server.
[mocap4r2_optitrack_driver_main-1] 
[mocap4r2_optitrack_driver_main-1] [NatNetLib] [ERROR]: Socket error 107: Transport endpoint is not connected
```

I tested the code on a Docker using the 'host' network mode with ROS Humble and on Ubuntu 24.04 with ROS jazzy. I tried compiling with C++14 and 17. I  can confirm that the `client_params` are the same before connect on both the SampleClient and MOCAP4ROS2. And I am out of ideas :)

Edit: Fix IP in SampleClient. Both 192.168.0.246 and .192.168.0.150 were tested and the results were the same. Working for SampleClient and not working for the node.

**Comment by aaggj** [comment]
Hi @dvdmc, could you paste the config file that you are using in order to discard possible issues with the configuration? Thank you in advance.

**Comment by dvdmc** [comment]
Hi @aaggj here it is:

```
mocap4r2_optitrack_driver_node:
  ros__parameters:
    connection_type: "Multicast" # Unicast / Multicast
    server_address: "198.168.0.100"
    local_address: "192.168.0.150" # Tested with 192.168.0.150 and "" which lets NatNetSDK find the local address
    multicast_address: "239.255.42.99"
    server_command_port: 1510
    server_data_port: 1511
    rigid_body_name: "tello_dav"
    lastFrameNumber: 0
    frameCount: 0
    droppedFrameCount: 0
    n_markers: 0
    n_unlabeled_markers: 0
    qos_history_policy: "keep_all"         # keep_all / keep_last
    qos_reliability_policy: "best_effort"  # best_effort / reliable
    qos_depth: 10                         # 10 / 100 / 1000
```
